### ISSUE TITLE
Spec error in generated spec_helper.rb under Ruby 2.4.6

### ISSUE THREAD

**Issue by msbit** [zilverline/sequent#188]
Under 2.4.6:

```
$ bundle exec rspec

An error occurred while loading ./spec/app/projectors/post_projector_spec.rb.
Failure/Error: require_relative '../../spec_helper'

SyntaxError:
  /Users/tom/development/msbit/sequent-test/spec/spec_helper.rb:35: syntax error, unexpected keyword_ensure, expecting keyword_end
    ensure
          ^
  /Users/tom/development/msbit/sequent-test/spec/spec_helper.rb:44: syntax error, unexpected keyword_ensure, expecting keyword_end
      ensure
            ^
  /Users/tom/development/msbit/sequent-test/spec/spec_helper.rb:47: syntax error, unexpected keyword_end, expecting end-of-input
    end
       ^
# ./spec/app/projectors/post_projector_spec.rb:1:in `require_relative'
# ./spec/app/projectors/post_projector_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/lib/post/post_command_handler_spec.rb.
Failure/Error: require_relative '../../spec_helper'

SyntaxError:
  /Users/tom/development/msbit/sequent-test/spec/spec_helper.rb:35: syntax error, unexpected keyword_ensure, expecting keyword_end
    ensure
          ^
  /Users/tom/development/msbit/sequent-test/spec/spec_helper.rb:44: syntax error, unexpected keyword_ensure, expecting keyword_end
      ensure
            ^
  /Users/tom/development/msbit/sequent-test/spec/spec_helper.rb:47: syntax error, unexpected keyword_end, expecting end-of-input
    end
       ^
# ./spec/lib/post/post_command_handler_spec.rb:1:in `require_relative'
# ./spec/lib/post/post_command_handler_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00036 seconds (files took 0.07237 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

```

Under 2.5.5:

```
$ bundle exec rspec
...

Finished in 0.15 seconds (files took 0.81271 seconds to load)
3 examples, 0 failures

```

Likely due to:

```
rescue/else/ensure are now allowed to be used directly with do/end blocks.
```

added as part of 2.5.0.

This might simply be a matter of changing:

```
Sequent require Ruby version 2.3.7 or later.
```

on https://www.sequent.io/docs/getting-started.html

**Comment by lvonk** [comment]
Thanks for spotting this. Changed the readme to reflect this.
