### ISSUE TITLE
Errors encountered in Getting Started guide

### ISSUE THREAD

**Issue by reentim** [zilverline/sequent#196]
At the end of section 1.1, `bundle exec rspec` runs into some uninitialized constant errors.

* ruby 2.6.3p62
* PostgreSQL 11.2
* sequent (3.2.2)

```
$ bundle exec rspec

An error occurred while loading ./spec/app/projectors/post_projector_spec.rb.
Failure/Error: require 'sequent/test'

NameError:
  uninitialized constant Sequent::ApplicationRecord
# ./spec/spec_helper.rb:6:in `require'
# ./spec/spec_helper.rb:6:in `<top (required)>'
# ./spec/app/projectors/post_projector_spec.rb:1:in `require_relative'
# ./spec/app/projectors/post_projector_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/lib/post/post_command_handler_spec.rb.
Failure/Error: require 'sequent/test'

NameError:
  uninitialized constant Sequent::ApplicationRecord
# ./spec/spec_helper.rb:6:in `require'
# ./spec/spec_helper.rb:6:in `<top (required)>'
# ./spec/lib/post/post_command_handler_spec.rb:1:in `require_relative'
# ./spec/lib/post/post_command_handler_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.0002 seconds (files took 0.2669 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples
```

Repo here: https://github.com/reentim/blog

**Comment by lvonk** [comment]
Hi,

Thanks for reporting this. This will be fixed by https://github.com/zilverline/sequent/pull/195

**Comment by lvonk** [comment]
Hi @reentim,

The fix is merged in master. I tested it on your repo and it now works on my machine 👍 ;-)
