### ISSUE TITLE
bundle exec rake sequent:migrate:online fails citing no sequent_versions table

### ISSUE THREAD

**Issue by jarblz** [zilverline/sequent#205]
Hi there! I'm trying to add this to an existing rails application that already has some non event sourced seed data managed by activerecord.  I run through all of the steps on the getting started section

`bundle install`
`bundle exec rake sequent:db:create`
`RACK_ENV=test bundle exec rake sequent:db:create`
`bundle exec rake sequent:db:create_view_schema`

Everything is successful at this point, I did have to move a few things around and add some config options telling sequent where my database.yml lived, but then when i run 

`bundle exec rake sequent:migrate:online`

I get the following error:

```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "sequent_versions" does not exist
LINE 1: SELECT  "sequent_versions".* FROM "sequent_versions" ORDER B...
                                          ^
: SELECT  "sequent_versions".* FROM "sequent_versions" ORDER BY version desc LIMIT $1
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `async_exec_params'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `block (2 levels) in exec_no_cache'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:610:in `block in exec_no_cache'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_no_cache'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `execute_and_clear'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:478:in `select'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:106:in `select_all'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/querying.rb:41:in `find_by_sql'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/relation.rb:560:in `block in exec_queries'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/relation.rb:547:in `exec_queries'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/relation.rb:422:in `load'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/relation.rb:200:in `records'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/relation.rb:195:in `to_ary'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/relation/finder_methods.rb:532:in `find_nth_with_limit'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/relation/finder_methods.rb:517:in `find_nth'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/relation/finder_methods.rb:125:in `first'
/Users/jared/.rvm/gems/ruby-2.6.4/bundler/gems/sequent-559b2f259d5a/lib/sequent/migrations/view_schema.rb:87:in `current_version'
/Users/jared/.rvm/gems/ruby-2.6.4/bundler/gems/sequent-559b2f259d5a/lib/sequent/migrations/view_schema.rb:304:in `drop_old_tables'
/Users/jared/.rvm/gems/ruby-2.6.4/bundler/gems/sequent-559b2f259d5a/lib/sequent/migrations/view_schema.rb:275:in `rollback_migration'
/Users/jared/.rvm/gems/ruby-2.6.4/bundler/gems/sequent-559b2f259d5a/lib/sequent/migrations/view_schema.rb:163:in `rescue in migrate_online'
/Users/jared/.rvm/gems/ruby-2.6.4/bundler/gems/sequent-559b2f259d5a/lib/sequent/migrations/view_schema.rb:147:in `migrate_online'
/Users/jared/.rvm/gems/ruby-2.6.4/bundler/gems/sequent-559b2f259d5a/lib/sequent/rake/migration_tasks.rb:91:in `block (3 levels) in register_tasks!'
/Users/jared/.rvm/gems/ruby-2.6.4/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/jared/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `eval'
/Users/jared/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `<main>'
```
I looked in my database and I do have a `view_schema` group with a `schema_versions` table, but for some reason the migration task can't see it.  I don't think this has something to do with the existing database i have set up, because I can drop everything and run the sequent specific commands first and it still fails.

Any thoughts?

Thanks!

**Comment by jarblz** [comment]
gemfile:

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.4'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.3'
gem 'bundler', '~> 2.0.1'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# json web token decoding  library
gem 'jwt'
gem 'airtable'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'
gem 'sequent', git: 'https://github.com/zilverline/sequent'


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry-rails'
  gem 'dotenv-rails'
  gem 'foreman'
end

group :test do
  gem 'rspec'
  gem "rspec_junit_formatter"
  gem 'rspec-rails', '~> 3.0'
  # Factory Bot and Faker for generating test data
  gem 'factory_bot_rails', '~> 4.8'
  gem 'faker', '~> 1.9'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'vcr'
  gem 'webmock'

end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by lvonk** [comment]
Does your database config (typically location at `#{Sequent.database_config_directory}/database.yml`) contain the correct `schema_search_path`? So meaning it includes the `view_schema`?

**Comment by lvonk** [comment]
@jarblz Is this still an issue? Did you try https://github.com/zilverline/sequent/issues/205#issuecomment-540035990?

**Comment by lvonk** [comment]
Closing due to inactivity. If this is still an issue please let us know.

**Comment by vsoloopben** [comment]
@lvonk We have come across the same issue when we try to use sequent in out rails application.
`schema_search_path` has already been set like this "public,sequent_schema,view_schema"

However, it will only work in first few requests, seem rails will only try to execute the `SET search_path TO ...` query once, and this query will only take effect on current session only.

Reference here: http://www.postgresonline.com/article_pfriendly/279.html
We turn out need to manually set search_path at Database level (`ALTER DATABASE mydb SET search_path = ...`) to workaround this issue.
This is not ideal at all. Just wonder if there are any better solution?

**Comment by lvonk** [comment]
Hi @vsoloopben,

Thanks for reporting. I reopened the issue. 

I have created an example [Rails & Sequent application](https://github.com/zilverline/sequent-examples) and a [step by step guide](https://www.sequent.io/docs/rails-sequent.html) on how to add Sequent in an existing Rails application. This seems to work fine, also with running multiple  (Sequent and Rails) migrations.

Could you verify that you have a similar setup?

**Comment by lvonk** [comment]
Closing due to inactivity. If this is still an issue please let us know.
